# Generated by Django 4.1.7 on 2023-04-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracked_time", "0002_trackedtime_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedtime",
            name="type_of_input",
            field=models.IntegerField(
                choices=[(0, "Clock"), (1, "Task"), (2, "Manual")]
            ),
        ),
    ]
