# Generated by Django 4.1.7 on 2023-04-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracked_time", "0004_alter_trackedtime_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedtime",
            name="all_day",
            field=models.BooleanField(default=False),
        ),
    ]
