# Generated by Django 4.1.7 on 2023-04-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracked_time", "0005_trackedtime_all_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedtime",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
