# Generated by Django 4.1.7 on 2023-04-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracked_time", "0009_alter_trackedtime_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedtime",
            name="start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
