# Generated by Django 4.1.7 on 2023-04-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("01", "Kranheit"),
                            ("02", "Unfall"),
                            ("03", "Ferien"),
                            ("04", "Urlaub bezahlt"),
                            ("05", "Urlaub unbezahlt"),
                            ("06", "Militär, Zivilschutz"),
                            ("07", "Dienstreise"),
                            ("08", "Ausbildung"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
        ),
    ]
