# Generated by Django 4.1.7 on 2023-04-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_project_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tag_color",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
